Atalhos para o terminal

ctrl+alt+t-para entrar no terminal
ctrl+alt+f1-atalho puro para o terinal
crtl+alt+f7-para voltar
$- significa usuario comum
#- significa super usuaria
~- significa seu usuario
ls- lista de todos os dados
ls lh- listar arquivos da diretoria
ctrl+l-limpar
cd+/-diretorio raiz
cd+--para sair do diretorio raiz
azul-diretorio
verde-linksimbolico/atalho
cinza-arquivos
marca texto-perigo
pwd-diretorio corrente
mkdir-para criar diretorios
tab-ele alto completa o comando
