Atalhos para o terminal

ctrl+alt+t-para entrar no terminal
ctrl+alt+f1-atalho puro para o terinal
crtl+alt+f7-para voltar
$- significa usuario comum
#- significa super usuaria
~- significa seu usuario
ls- lista de todos os dados
ls lh- listar arquivos da diretoria
ctrl+l-limpar
cd+/-diretorio raiz
cd+--para sair do diretorio raiz
azul-diretorio
verde-linksimbolico/atalho
cinza-arquivos
marca texto-perigo
pwd-diretorio corrente
mkdir-para criar diretorios
tab-ele alto completa o comando
sudo apt update-para atualizar
sudo apt update && sudo apt install-para atualizar e instalar aplicativo
&&-continuar comando na mesma linha
echo-imprimi a tela o que você esta querendo
touch-muda data e hora do arquivo e caso não exista ele cria 
cat- para listar o conteudo do arquivo
cat -n-lista o conteudo
674 conteudo
head -n LICENSE-para ler as linhas do começo
tail -n LICENSE-para ler as linhas finais
less- paginador
|-para separar o proximo comando
